hotwax/vsf-peregrine

.gitignore
README.md

Additional change:
Added editor specific files in .gitignore
closes #1

Add installation instructions to README.md #1

---

components/ComponentRenderer.vue
pages/SizeGuide.vue

1. udated component cmsRender to componentRenderer.
2. updated store name cmsPeregrine to cmsstore.
additonal change: add null or empty check in ComponentRenderer component

size-guide modal is not working on product-detail page #14

---

components/HeadImage.vue
components/MainSlider.vue
components/PromotedOffers.vue
components/TileLinks.vue

1. check imageLinkType is internalLink then add config cms-peregrine image endpoint
2. if imageLinkType is url or '' then provide image link

Internal and external Image url support #23

---

components/BestSeller.vue
components/ComponentRenderer.vue

1. create a best seller component in vsf-peregrine.
2. added a state in homepage module in the vue-storefront.
3. import best seller component on componentRenderer component.

implement : best seller component for VSF

---

components/PromotedOffers.vue
store/action.ts

closes #28
[1] Changed URL structure from url.20.json to url.data.json
[2] Improved promotedOffers component as JSON structure got changed while fetching data using url.data.json

Improved: changed the url structure of peregrine cms

---

components/BannerLeft.vue
components/ComponentRenderer.vue

The banner left component will have content on the left and image on the right followed by the button.
closes #31

Implemented: banner left component for the cms (#31)

---

components/BestSeller.vue
components/HeadImage.vue
components/MainSlider.vue
components/MediaObjects.vue
components/NewArrivalProduct.vue
components/RichText.vue
components/SimpleText.vue
components/TileLinks.vue
hooks/afterRegistration.ts
hooks/beforeRegistration.ts
mixins/ComponentFilterMixin.js
pages/Home.vue
pages/SizeGuide.vue
pages/Static.vue
router/beforeEach.ts
store/action.ts
store/state.ts

Fixed: Indentation issues identified by vslint (#33)

---

components/ComponentRenderer.vue
components/VerticalGrid.vue

Implemented: Vertical Banner Grid component for the CMS (#39)

---

components/ComponentRenderer.vue
components/HorizontalTwins.vue

Horizontal Twins component is having two cards each one is having a title and button on the left side.

Implemented: Horizontal Twins component for the CMS (#36)

---

components/BannerRight.vue
components/ComponentRenderer.vue

The BannerRight component will have content and button on the right and image on the left side.

Implemented: BannerRight component for the cms (#35)

---

components/ComponentRenderer.vue
components/TGrid.vue

Implemented: TGrid component for the CMS (#37)

---

components/AppStore.vue
components/ComponentRenderer.vue

AppStoreLink component is having links for downloading the application from App Store and Play Store.

Implemented: AppStore Link component for the CMS (#42)

---

components/ComponentRenderer.vue
components/Newsletter.vue

Implemented: Newsletter component for the CMS(#41)

---

components/AppStore.vue
components/BannerLeft.vue
components/BannerRight.vue
components/FourCardLayout.vue
components/HorizontalTwins.vue
components/Newsletter.vue
components/TGrid.vue
components/VerticalGrid.vue
mixins/LinkMixin.js

Linked the components and buttons with links on the basis of whether the links are empty or not. If the link for the buttons is empty then the button will not get displayed.

Updated: Linked components and buttons with their links (#43)

---

components/CmsPage.vue
components/organisms/o-text-block.vue

Here is output view
CC: @mohammad-k8, @iamaishwary

Implemented Text Block component using Storefront UI (3bpy9t)

---

index.ts
store/index.ts

Thanks: @mohammad-k8 for reporting.

Improved: Renamed the Peregrine store to peregrineStore from module for better readability

---

components/CmsPage.vue
components/organisms/o-newsletter.vue

Screenshot of the Newsletter component:
app.clickup.com/t/3btkez

Implemented: Newsletter component using Storefront UI (#3btkez)

---

README.md

New READMe file, looks like this
https://github.com/hotwax/vsf-peregrine/blob/%2339u185/README.md

Updated the README file as per the Vue Storefront 1.12 version (39u185)

---

README.md
helper/PeregrineConfig.js
mixins/imageMixin.js
store/action.ts

Updated the README file as well.

Improved: Moved the Peregrine CMS config from global file to respective module (3fp9wy)

---

README.md
pages/Home.vue

This page is inspired by VSF-Capybara theme
https://github.com/DivanteLtd/vsf-capybara/blob/develop/pages/Home.vue
From this, the unused components are removed.
Updated README file too.

Implemented: Home page to honor the CMS components (3fvcrq)

---

components/CmsPage.vue
components/molecules/m-banner.vue
components/organisms/o-banner-grid-t.vue
components/organisms/o-banner-grid.vue
components/organisms/o-text-block.vue
pages/Home.vue
pages/Static.vue
store/mutations.ts
types/CmsState.ts

Fixed lint issues

---

components/CmsPage.vue
components/molecules/m-banner.vue
components/organisms/o-banner-grid-t.vue
components/organisms/o-banner-grid.vue
components/organisms/o-newsletter.vue
components/organisms/o-text-block.vue
hooks/afterRegistration.ts
hooks/beforeRegistration.ts
index.ts
store/action.ts

Thanks, @mohammad-k8 for reporting.

Fixed lint issues (3huj84)

---

components/CmsPage.vue
components/organisms/o-images-grid.vue

The code is inspired by Capybara theme's image grid
https://github.com/DivanteLtd/vsf-capybara/blob/develop/components/atoms/a-images-grid.vue

Implemented: Image Grid component (3btknj)

---

components/CmsPage.vue
components/organisms/o-carousel.vue

Ticket link - https://app.clickup.com/t/3btkpr
Carousel Screenshot

Implemented: Carousel component using Storefront UI (#3btkpr)

---

components/organisms/o-newsletter.vue

Closes https://app.clickup.com/t/15dn7x
Added the missing code for opening the modal.

Fixed: Subscription modal were not showing on Subscribe button (15dn7x)

---

components/CmsPage.vue
pages/Home.vue
pages/Static.vue

Added safe area rules in global max-width class, hence improved the class name.
closes https://app.clickup.com/t/1b73g8

Improved: Replaced max-width class name with main-content(#1b73g8)

---

components/CmsPage.vue
components/organisms/o-banner-grid.vue
components/organisms/o-carousel.vue
components/organisms/o-images-grid.vue
helper/PeregrineConfig.js

Ticket ID: https://app.clickup.com/t/1fd0u8
As per the new Peregrine version 2.0 the directory structure is changed, also JSON schema for the various component is refactored.
Thus update the module to honor these changes. With this we were able to remove some extra code we have written on client side.

Improved: Updated the vsf-peregrine module to honor new Peregrine CMS version 2.0 (1fd0u8)

---

pages/Static.vue

Removed if condition of the static content from the div, having class for min height.
Added the if condition on the cms content itself

Fixed: Min height of the staticv page (#1h9a8v)

---

CHANGELOG.md
components/organisms/o-product-carousel.vue

Added wishlist icon and its functionality on search results and on product carousels
Before
After

Added: Wishlist functionality on search results and on product carousels (#1h9aeu)

---

components/CmsPage.vue
pages/Static.vue

1. Defined CmsPage as a functional component and passing the components as a prop to it.

[WIP] Improved: code by defining CmsPage as functional and passing the components as a prop(#2bc303)

---

changelogs/unreleased/-9512zk.yml
mixins/LinkMixin.js

- Added a common method that handles both the cases for button links as well as normal links
- Added a condition to check for if the link starts with collections and then handle the case separately

Updated code to handle the cms component links properly

---

patches/Peregrine.patch

- Moved the peregrine register module line above as it has conflicts with Braintree patch

Updated: peregrine patch to resolve conflicts with braintree patches(patch-update)

---

changelogs/unreleased/-cqgxfe.yml
components/organisms/o-horizontal-twins.vue
pages/Static.vue

Implemented: horizontal twins component for peregrine(#cqgxfe)

---

components/molecules/m-banner.vue
components/organisms/o-banner-grid-t.vue
components/organisms/o-carousel.vue
components/organisms/o-horizontal-twins.vue

- Added storefront CSS in the horizontal twins component
- Added storefront CSS in the banner-grid-t component
- Updated text styling for some components

Improved the code for components and linked the text styling(#cx5jd7)
